### ISSUE TITLE
54510875 - Rio

### ISSUE THREAD

**Issue by wheelmac92** [xenia-project/game-compatibility#1481]
![image](https://user-images.githubusercontent.com/58401060/71495136-43348e80-281a-11ea-926a-86c8716a7244.png)

Goes into game with occasional crashes. Crashed when I uploaded this screenshot. Almost no bugs (except for rare crashes)

**Comment by Sleepy93** [comment]
Well guys :) Should I corrigate this issue :) 

# Marketplace
ID is: #54510875
[Marketplace](https://marketplace.xbox.com/en-US/Product/Rio/66acd000-77fe-1000-9115-d80254510875)

Game goes into gameplay but sometimes it causes crashes.
I tried to play 4 times with this game via Xenia, once it worked good but other times xenia crashed or windows died..

# Tested 
On (https://github.com/xenia-project/xenia/commit/c43ccc073da10fcf2ba43c4f90746cbc9b26880d)

# Issues
!> 00000028 ResolvePath(UPDATE:\PATCH0.BIN) failed - device not found
!> 00000028 ResolvePath(\Device\Harddisk0\) failed - device not found
!> 00000190 XMA: Write to unhandled register (0601): 00000002

# Undefined
!> 00000028 undefined extern call to 82757628 NetDll_XNetGetBroadcastVersionStatus
!> 00000028 undefined extern call to 827575C8 NetDll_XNetCreateKey
!> 00000028 undefined extern call to 827575D8 NetDll_XNetRegisterKey

# Unimplemented
- XFileSectorInformation
- XamPartyGetUserList
- XamPartySendGameInvites
- XamPartySetCustomData
- XamPartyGetBandwidth
- XamShowPartyUI
- XamShowCommunitySessionsUI

# GPU
Writes to unk. register
- 0081
- 0082
- 1E4E

# Log file
[Rio.zip](https://github.com/xenia-project/game-compatibility/files/4009871/Rio.zip)

![rio_intro](https://user-images.githubusercontent.com/20132031/71583819-585a3780-2b10-11ea-956d-dea000f1ce61.png)
![rio_intro2](https://user-images.githubusercontent.com/20132031/71583822-5abc9180-2b10-11ea-8794-e0264a4d66f7.png)
![rio_menus](https://user-images.githubusercontent.com/20132031/71583825-5e501880-2b10-11ea-9064-3a2eede33e14.png)
![rio_menus2](https://user-images.githubusercontent.com/20132031/71583834-6314cc80-2b10-11ea-804d-7e722bd30b21.png)
![rio_game](https://user-images.githubusercontent.com/20132031/71583840-65772680-2b10-11ea-9236-ccb62c9e4078.png)

# Labels
- state-gameplay
- kernel-unimplemented-feature
- state-crash-obsolate (?) - I don't know what happened when windows crashed because it lost all logs and filled the log file via NULL chars.

**Comment by Margen67** [comment]
@Sleepy93 You should post that in a new issue.

**Comment by Margen67** [comment]
#1484
