### ISSUE TITLE
Top Spin 4 crash

### ISSUE THREAD

**Issue by Elwe8** [xenia-project/game-compatibility#728]
Hi guys, i downloaded top spin 4 xbox 360 version: iXtreme (6th wave), and downloaded latest update xenia emulator, but loading screen after game crashed and fonts changed like that;
![xen111](https://cloud.githubusercontent.com/assets/25799768/22986335/d72f7648-f3b3-11e6-9096-e544d30aaf43.jpg)
I would be glad if you help, thanks.

**Comment by rlabrecque** [comment]
Did you read the README file?
https://github.com/xenia-project/game-compatibility/blob/master/README.md

Because you didn't use the issue template.
https://github.com/xenia-project/game-compatibility/blob/master/.github/ISSUE_TEMPLATE.md

And don't say that you pirated a game. That's just dumb Emir.

**Comment by Elwe8** [comment]
Okey understand, just delete my post and my profile, i dont want anything help.

**Comment by Razzile** [comment]
closing until it follows the template
